[package]
name = "asciidoc-static-pages"
version = "0.1.0"
edition = "2021"
description = "AsciiDoc 文档渲染工具"
license = "MIT"

[dependencies]
yaml-rust = "0.4"
clap = { version = "3.2.16", features = ["derive"] }
git2 = "0.15"
