FROM  asciidoctor/docker-asciidoctor:1.27
RUN apk add git && gem install rouge asciidoctor-kroki
COPY target/x86_64-unknown-linux-musl/release/asciidoc-static-pages /usr/local/bin/asciidoc-static-pages
COPY target/x86_64-unknown-linux-musl/release/asciidoc-static-pages /usr/local/bin/pages
